---
- name: Install RPM packages
  dnf:
      name:
      - httpd
      - python3-mod_wsgi
      - fedora-messaging
      - gcc
      - git
      - poetry
      - python3-cryptography
      - python3-devel
      - python3-pip
      state: present

- name: get noggin
  git:
    repo: https://github.com/fedora-infra/noggin.git
    dest: /vagrant/noggin
  become: True
  become_user: vagrant

- name: install noggin with poetry
  shell: poetry install
  become: True
  become_user: vagrant
  register: poetry_output
  changed_when: "'No dependencies to install or update' not in poetry_output.stdout"
  args:
    chdir: /vagrant/noggin

- name: stuff noggin virtualenv into a variable
  shell:
    cmd: poetry env info -p
  become: True
  become_user: vagrant
  register: poetry_virtualenv_path
  changed_when: False
  args:
    chdir: /vagrant/noggin

- name: Install the bashrc
  copy:
    src: bashrc
    dest: /etc/profile.d/vagrant-noggin.sh
    mode: 0644
    owner: root
    group: root

- name: Install noggin.cfg
  template:
    src: noggin.cfg
    dest: /etc/noggin.cfg

- name: Copy wsgi
  copy:
    src: noggin.wsgi
    dest: /srv/noggin.wsgi
    mode: 0644
    owner: vagrant
    group: vagrant
  notify:
    - restart httpd

- name: compile the translations
  command:
    cmd: poetry run pybabel compile -d ./noggin/translations
    chdir: /vagrant/noggin
    creates: /vagrant/noggin/noggin/translations/fr_FR/LC_MESSAGES/messages.mo
  become: True
  become_user: vagrant

- name: Create the log directory
  file:
    path: /var/log/noggin
    state: directory
    owner: apache
    group: apache
    mode: 0755

- name: Allow apache to log to Noggin's log dir
  community.general.sefcontext:
    target: "/var/log/noggin(/.*)?"
    setype: httpd_log_t

- name: Apply new SELinux file context to Noggin's log dir
  ansible.builtin.command: restorecon -irv /var/log/noggin
  register: restorecon_result
  changed_when: restorecon_result.stdout != ""

- name: Copy configs for Apache
  template:
    src: httpd.conf
    dest: /etc/httpd/conf.d/noggin.conf
  notify:
    - restart httpd

- name: Enable and restart Apache
  systemd:
    state: restarted
    name: httpd
    enabled: yes
    daemon_reload: yes
