---
- name: Install packages
  package:
      name: "{{ item }}"
      state: present
  with_items:
      - rabbitmq-server

- name: Create RabbitMQ systemd override directory
  file:
    path: /etc/systemd/system/rabbitmq-server.service.d/
    state: directory

- name: Override rabbitmq hostname
  copy:
    content: "HOSTNAME=localhost"
    dest: /etc/rabbitmq/rabbitmq-env.conf
    mode: 0644
  notify:
    - reload rabbitmq

- name: Override file limit on rabbitmq
  copy:
    content: "[Service]\nLimitNOFILE=500000\n"
    dest: /etc/systemd/system/rabbitmq-server.service.d/override.conf
  notify:
    - reload rabbitmq

- name: start rabbitmq
  service: name=rabbitmq-server state=started enabled=yes

- name: Create a guest user in RabbitMQ
  rabbitmq_user:
    user: fedoramessages
    password: fedoramessages
    tags: administrator
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  notify:
    - reload rabbitmq

# fedora-messaging-logger is a simple service that logs all messages to journal
# so you can go back and easily see all messages sent here
- name: Install the systemd unit files for the fedora-messaging-logger service
  copy:
      src: fedora-messaging-logger.service
      dest: /etc/systemd/system/fedora-messaging-logger.service
      mode: 0644

- name: Start fedora-messaging-logger service using systemd
  systemd:
    state: started
    name: fedora-messaging-logger
    daemon_reload: yes
    enabled: yes

- name: Install the .bashrc
  copy:
      src: .bashrc
      dest: /home/vagrant/.bashrc
      mode: 0644
      owner: vagrant
      group: vagrant