---
- name: Install RPM packages
  dnf:
    name:
      - httpd
      - krb5-workstation
      - sqlite
      - openssl
      - mod_ssl
    state: present

- name: kinit for Apache
  shell: echo "{{ ipa_admin_password }}" | kinit {{ ipa_admin_user }}@{{ krb_realm }}
  changed_when: False

- name: Get the certificates
  import_role:
    name: cert
  vars:
    cert_hostname: "{{ ansible_fqdn }}"
    cert_basename: server

- name: configure SSLCertificateFile in ssl.conf
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: "SSLCertificateFile \/etc\/pki\/tls\/certs\/localhost.crt"
    line: SSLCertificateFile /etc/pki/tls/certs/server.pem
  notify: restart httpd

- name: configure SSLCertificateKeyFile in ssl.conf
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: "SSLCertificateKeyFile \/etc\/pki\/tls\/private\/localhost.key"
    line: SSLCertificateKeyFile /etc/pki/tls/private/server.key
  notify: restart httpd

- name: set default client keytab in krb5.conf
  lineinfile:
    path: /etc/krb5.conf
    insertafter: 'default_ccache_name.*'
    line: '  default_client_keytab_name = FILE:{{ keytab_path }}'

- name: redirect to https
  copy:
    src: redirect-to-ssl.conf
    dest: /etc/httpd/conf.d/redirect-to-ssl.conf
  notify: restart httpd

- name: Tune SELinux Policy
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items:
    - httpd_can_network_connect
    - httpd_read_user_content
  notify:
    - restart httpd

- name: Allow apache to see /srv
  community.general.sefcontext:
    target: "/srv(/.*)?"
    setype: httpd_sys_content_t

- name: Allow apache to execute binary python libraries
  community.general.sefcontext:
    target: "/home/vagrant/.cache/pypoetry/virtualenvs/.*\\.so"
    setype: httpd_sys_script_exec_t

- name: Allow apache to execute binary python libraries
  community.general.sefcontext:
    target: "/home/vagrant/.cache/pypoetry/virtualenvs/.*\\.so"
    setype: httpd_sys_script_exec_t

- name: Apply new SELinux file context to the poetry virtualenvs
  ansible.builtin.command: restorecon -irv /home/vagrant/.cache/pypoetry/virtualenvs
  register: restorecon_result
  changed_when: restorecon_result.stdout != ""

- name: Enable and restart Apache
  systemd:
    state: restarted
    name: httpd
    enabled: yes
    daemon_reload: yes
