---

- name: Install Pagure milter packages
  dnf:
    name:
      - postfix
      - python3-pymilter
    state: present
    enablerepo: updates-testing

- name: Start Postfix
  service: name=postfix state=started enabled=yes
