- name: Generate and get SSL cert
  shell: ipa-getcert request -f /data/etc/pki/tls/certs/{{ cert_basename }}.pem -k /data/etc/pki/tls/certs/{{ cert_basename }}.key -K {{ krb_service }}/{{ cert_hostname }} -N {{ cert_hostname }} -O {{ cert_owner }} -o {{ cert_owner }}
  args:
    creates: /data/etc/pki/tls/certs/{{ cert_basename }}.pem

- name: Check the cert is there
  wait_for:
    path: /data/etc/pki/tls/certs/{{ cert_basename }}.pem
    state: present

- name: Check the key is there
  wait_for:
    path: /data/etc/pki/tls/certs/{{ cert_basename }}.key
    state: present
