---
# *src.tinystage.test*  is a machine that runs pagure to replicate src.fedoraproject.org
- hosts: src
  become: true
  become_method: sudo
  roles:
    - common
    - ipa-client
    - cert
    - src
